apiVersion: apps/v1
kind: Deployment
metadata:
  name: creavio-api-gateway-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creavio-api-gateway-dev
  template:
    metadata:
      labels:
        app: creavio-api-gateway-dev
    spec:
      containers:
        - name: creavio-api-gateway-dev
          image: creavio-api-gateway-dev:latest
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
          ports:
            - containerPort: 8000
          env:
            - name: USER_SERVICE_URL
              value: http://user-service-dev:8001
            - name: NOTIFICATION_SERVICE_URL
              value: http://notification-service-dev::8002

---
apiVersion: v1
kind: Service
metadata:
  name: creavio-api-gateway-dev
spec:
  type: ClusterIP
  selector:
    app: creavio-api-gateway-dev
  ports:
    - name: http
      port: 8000
      targetPort: 8000